### ISSUE TITLE
SSMAgentcf.yaml - Failing on run

### ISSUE THREAD

**Issue by Talderon** [Talderon/AWS_CloudFormation#1]
Current Error:

MaintenanceWindowTarget |  CREATE_FAILED | Property validation failure: [Value of property {/Targets/0/Values} does not match type {Array}]

As most people who use CF know, this is a pretty generic error. Working through it now.

**Comment by Talderon** [comment]
The issue lied in the Targets section:
```
      Targets:
        - Key: !Ref MaintenanceTargetTarget
          Values: !Ref MaintenaneTargetKeyValue
```
The above was incorrect. Below is the correction:
```
      Targets:
        - Key: !Ref MaintenanceTargetTarget
          Values: 
          - !Ref MaintenaneTargetKeyValue
```
Hope this helps others!!
