### ISSUE TITLE
Template error when using S3 Logging section

### ISSUE THREAD

**Issue by Talderon** [Talderon/AWS_CloudFormation#2]
MaintenanceWindowRunCommandTask |  CREATE_FAILED | Property validation failure: [Encountered unsupported properties in {/}: [DocumentHashType, NotificationConfig, OutputS3BucketName, DocumentHash]]

**Comment by Talderon** [comment]
Also manifests here: Property validation failure: [Encountered unsupported properties in {/}: [DocumentHashType, OutputS3KeyPrefix, NotificationConfig, OutputS3BucketName, DocumentHash]]

Tried Bucket Name and Bucket ARN

**Comment by Talderon** [comment]
Parameters:

```
  MaintenanceTargetS3BucketPrefix:
    Description: The Amazon S3 bucket subfolder (Optional, can be removed)
    Type: String
  MaintenanceWindowRunCommandTaskName:
    Description: Maintenace Window Task Name (No Spaces)
    Type: String
```
Resources:
```
      OutputS3BucketName: !Ref MaintenanceTargetS3Bucket
      OutputS3KeyPrefix: !Ref MaintenanceTargetS3BucketPrefix
```

**Comment by Talderon** [comment]
Looks like it is having an issue with everything for the Task Type: RUN_COMMAND (snippet below)

Parameters:
 ```
 MaintenanceWindowRunCommandTaskName:
    Description: Maintenace Window Task Name (No Spaces)
    Type: String
  MaintenanceWindowRunCommandTaskPriority:
    Description: Job Priority - Number 0 - 5
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 5
  MaintenanceWindowRunCommandTaskMaxConcurrency:
    Description: Integer or Percentage
    Type: String
    Default: 50%
    AllowedPattern: ^([1-9][0-9]*|[1-9][0-9]%|[1-9]%|100%)$
  MaintenanceWindowRunCommandTaskMaxErrors:
    Description: Integer or Percentage
    Type: String
    Default: 25%
    AllowedPattern: ^([1-9][0-9]*|[1-9][0-9]%|[1-9]%|100%)$
  MaintenanceServiceRoleArn:
    Description: The ARN of the IAM service role to use to publish Amazon Simple Notification Service (Amazon SNS) notifications for maintenance window Run Command tasks.
    Type: String
    Default: arn:aws:iam::{AccountId}:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM
```
Resources:
```
  MaintenanceWindowRunCommandTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      WindowId: !Ref MaintenanceWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref MaintenanceWindowTarget
      TaskArn: AWS-UpdateSSMAgent
      ServiceRoleArn: !Ref MaintenanceServiceRoleArn
      TaskType: RUN_COMMAND
      DocumentHash: 53c06c366cf29363cdbd1c9bb6b8cf212b9172a14e763b37036c281c8880c063
      DocumentHashType: Sha256
      NotificationConfig:
        NotificationArn: !Ref MaintenanceTargetSNSARN
        NotificationEvents: All
        NotificationType: Command
      OutputS3BucketName: !Ref MaintenanceTargetS3Bucket
      OutputS3KeyPrefix: !Ref MaintenanceTargetS3BucketPrefix
      Priority: !Ref MaintenanceWindowRunCommandTaskPriority
      MaxConcurrency: !Ref MaintenanceWindowRunCommandTaskMaxConcurrency
      MaxErrors: !Ref MaintenanceWindowRunCommandTaskMaxErrors
      Name: !Ref MaintenanceWindowRunCommandTaskName
```

**Comment by Talderon** [comment]
If I switch the STEP_FUNCTION and use dummy information, it seems to work, but not as a RUN_COMMAND

**Comment by Talderon** [comment]
Reddit Post in r/aws: https://www.reddit.com/r/aws/comments/df4jcn/ssm_cloudformation_and_run_command_issues/

**Comment by Talderon** [comment]
Most recent iteration: (PasteBin): https://pastebin.com/GhUeyea8

**Comment by Talderon** [comment]
Found cfn-lint tool. Scanned - Output:

```
cfn-lint .\SSMAgent_cf.yaml
E3002 Invalid Property Resources/MaintenanceWindowRunCommandTask/Properties/DocumentHash
.\SSMAgent_cf.yaml:115:7

E3002 Invalid Property Resources/MaintenanceWindowRunCommandTask/Properties/DocumentHashType
.\SSMAgent_cf.yaml:116:7

E3002 Invalid Property Resources/MaintenanceWindowRunCommandTask/Properties/NotificationConfig
.\SSMAgent_cf.yaml:117:7

E3002 Invalid Property Resources/MaintenanceWindowRunCommandTask/Properties/OutputS3BucketName
.\SSMAgent_cf.yaml:121:7

E3002 Invalid Property Resources/MaintenanceWindowRunCommandTask/Properties/OutputS3KeyPrefix
.\SSMAgent_cf.yaml:122:7
```

Looking into the results.

**Comment by Talderon** [comment]
Fixed above issue by adding "TaskParameters" section, see below:

```
  MaintenanceWindowRunCommandTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      WindowId: !Ref MaintenanceWindow
      Targets:
        - Key: !Ref MaintenanceTargetTarget
          Values:
            - !Ref MaintenanceWindowTarget
      TaskArn: AWS-UpdateSSMAgent
      ServiceRoleArn: !Ref MaintenanceServiceRoleArn
      TaskType: RUN_COMMAND
      TaskParameters:
        DocumentHash: 53c06c366cf29363cdbd1c9bb6b8cf212b9172a14e763b37036c281c8880c063
        DocumentHashType: Sha256
        NotificationConfig:
          NotificationArn: !Ref MaintenanceTargetSNSARN
          NotificationEvents: 
            - All
          NotificationType: Command
        OutputS3BucketName: !Ref MaintenanceRunCommandS3Bucket
        OutputS3KeyPrefix: !Ref MaintenanceRunCommandS3BucketPrefix
      Priority: !Ref MaintenanceWindowRunCommandTaskPriority
      MaxConcurrency: !Ref MaintenanceWindowRunCommandTaskMaxConcurrency
      MaxErrors: !Ref MaintenanceWindowRunCommandTaskMaxErrors
      Name: !Ref MaintenanceWindowRunCommandTaskName
```

**Comment by Talderon** [comment]
cfn-lint comes back clean now

**Comment by Talderon** [comment]
Uploaded template and re-tested, came back with the following error:

MaintenanceWindowRunCommandTask | CREATE_FAILED | Can not construct instance of com.amazonaws.services.ssm.model.MaintenanceWindowTaskParameterValueExpression: no String-argument constructor/factory method to deserialize from String value ('test-') at [Source: N/A; line: -1, column: -1] (through reference chain: com.amazonaws.services.ssm.model.RegisterTaskWithMaintenanceWindowRequest["TaskParameters"]->java.util.LinkedHashMap["OutputS3KeyPrefix"])

Deciding if this is an extension of this issue or if it is a new issue.

**Comment by Talderon** [comment]
For shits and giggles, I removed the  MaintenanceRunCommandS3BucketPrefix just to see if it would run without it, I am getting:
` Can  not construct instance of  com.amazonaws.services.ssm.model.MaintenanceWindowTaskParameterValueExpression:  no String-argument constructor/factory method to deserialize from  String value ('Sha256')  at [Source: N/A; line: -1, column: -1] (through reference chain:  com.amazonaws.services.ssm.model.RegisterTaskWithMaintenanceWindowRequest["TaskParameters"]->java.util.LinkedHashMap["DocumentHashType"]) `
So, at this point, there is something still pooched in the RUN_COMMAND  TaskParameters section.

**Comment by Talderon** [comment]
Well, another iteration. Seems like I got past, yet another, error, just to run face first into another.
Latest PasteBin:  https://pastebin.com/5kkHJL7e 
This time, you can get the others yourself. :P
Anyway, new error, and this one is outside the Task Params:
```
 MaintenanceWindowRunCommandTask |  CREATE_FAILED |  tag:AgentUpdate  is an invalid window task target type, use WindowTargetIds or  InstanceIds. There must be at least one task target specified, either  1-50 instance ids or 1-10 window target ids. (Service: AmazonSSM; Status  Code: 400; Error Code: ValidationException; Request ID:  2343f326-78a7-445d-a3c4-de52ce98cc25) 
```
Digging into this one now.

**Comment by Talderon** [comment]
Committed latest iteration with issues for safe keeping.

**Comment by Talderon** [comment]
Issue Resolved:

```
  MaintenanceTargetTarget:
    Description: Tag Key should equal 'AgentUpdate'
    Type: String
    Default: tag:AgentUpdate
  MaintenaneTargetKeyValue:
    Description: True or False
    Type: String
    Default: True
    AllowedValues:
      - True
      - False
```
```
  MaintenanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Properties:
      Name: !Ref MaintenanceTargetName
      Description: !Ref MaintenanceTargetDescription
      WindowId: !Ref MaintenanceWindow
      ResourceType: 'INSTANCE'
      Targets:
        - Key: !Ref MaintenanceTargetTarget
          Values: 
          - !Ref MaintenaneTargetKeyValue
  MaintenanceWindowRunCommandTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      WindowId: !Ref MaintenanceWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref MaintenanceWindowTarget
```

Uploading fixed versions
